import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        // Типографика Mergen: Gros Ventre только для логотипа, Plex Sans для интерфейса.
        sans: ['"IBM Plex Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
        logo: ['"Gros Ventre"', "Georgia", "serif"],
      },
      colors: {
        // Цвета читаются из CSS-переменных, поэтому темы меняются без переписывания классов.
        mg: {
          purple: "var(--mg-purple)",
          "purple-deep": "var(--mg-purple-deep)",
          "purple-2": "var(--mg-purple-2)",
          "purple-soft": "var(--mg-purple-soft)",
          "purple-soft-2": "var(--mg-purple-soft-2)",
            "purple-soft-3": "var(--mg-purple-soft-3)",
          lime: "var(--mg-lime)",
          "lime-soft": "var(--mg-lime-soft)",
          bg: "var(--mg-bg)",
          surface: "var(--mg-surface)",
          "surface-2": "var(--mg-surface-2)",
            "surface-3": "var(--mg-surface-3)",
          border: "var(--mg-border)",
          text: "var(--mg-text)",
          "text-2": "var(--mg-text-2)",
          "text-3": "var(--mg-text-3)",
          success: {
            bg: "var(--mg-success-bg)",
            fg: "var(--mg-success-fg)",
          },
          danger: {
            bg: "var(--mg-danger-bg)",
            fg: "var(--mg-danger-fg)",
          },
          info: {
            bg: "var(--mg-info-bg)",
            fg: "var(--mg-info-fg)",
          },
          warning: {
            bg: "var(--mg-warning-bg)",
            fg: "var(--mg-warning-fg)",
          },
            "completed":   { bg: "var(--mg-completed-bg)", tx: "var(--mg-completed-tx)" },
            "in-process":  { bg: "var(--mg-in-process-bg)", tx: "var(--mg-in-process-tx)" },
            "not-started": { bg: "var(--mg-not-started-bg)", tx: "var(--mg-not-started-tx)" },
            "overdue":     { bg: "var(--mg-overdue-bg)", tx: "var(--mg-overdue-tx)" },
        },
          nt: {
              surface: "var(--nt-surface)",
              "surface-dim": "var(--nt-surface-dim)",
              "surface-bright": "var(--nt-surface-bright)",
              "surface-container-lowest": "var(--nt-surface-container-lowest)",
              "surface-container-low": "var(--nt-surface-container-low)",
              "surface-container": "var(--nt-surface-container)",
              "surface-container-high": "var(--nt-surface-container-high)",
              "surface-container-highest": "var(--nt-surface-container-highest)",
              "on-surface": "var(--nt-on-surface)",
              "on-surface-variant": "var(--nt-on-surface-variant)",
              "inverse-surface": "var(--nt-inverse-surface)",
              "inverse-on-surface": "var(--nt-inverse-on-surface)",
              outline: "var(--nt-outline)",
              "outline-variant": "var(--nt-outline-variant)",
              "surface-tint": "var(--nt-surface-tint)",
              primary: "var(--nt-primary)",
              "on-primary": "var(--nt-on-primary)",
              "primary-container": "var(--nt-primary-container)",
              "on-primary-container": "var(--nt-on-primary-container)",
              "inverse-primary": "var(--nt-inverse-primary)",
              secondary: "var(--nt-secondary)",
              "on-secondary": "var(--nt-on-secondary)",
              "secondary-container": "var(--nt-secondary-container)",
              "on-secondary-container": "var(--nt-on-secondary-container)",
              tertiary: "var(--nt-tertiary)",
              "on-tertiary": "var(--nt-on-tertiary)",
              "tertiary-container": "var(--nt-tertiary-container)",
              "on-tertiary-container": "var(--nt-on-tertiary-container)",
              error: "var(--nt-error)",
              "on-error": "var(--nt-on-error)",
              "error-container": "var(--nt-error-container)",
              "on-error-container": "var(--nt-on-error-container)",
              "primary-fixed": "var(--nt-primary-fixed)",
              "primary-fixed-dim": "var(--nt-primary-fixed-dim)",
              "on-primary-fixed": "var(--nt-on-primary-fixed)",
              "on-primary-fixed-variant": "var(--nt-on-primary-fixed-variant)",
              "secondary-fixed": "var(--nt-secondary-fixed)",
              "secondary-fixed-dim": "var(--nt-secondary-fixed-dim)",
              "on-secondary-fixed": "var(--nt-on-secondary-fixed)",
              "on-secondary-fixed-variant": "var(--nt-on-secondary-fixed-variant)",
              "tertiary-fixed": "var(--nt-tertiary-fixed)",
              "tertiary-fixed-dim": "var(--nt-tertiary-fixed-dim)",
              "on-tertiary-fixed": "var(--nt-on-tertiary-fixed)",
              "on-tertiary-fixed-variant": "var(--nt-on-tertiary-fixed-variant)",
              background: "var(--nt-background)",
              "on-background": "var(--nt-on-background)",
              "surface-variant": "var(--nt-surface-variant)",
          },
      },
      borderRadius: {
        icon: "8px",
        control: "11px",
        panel: "14px",
        table: "16px",
        login: "26px",
      },
      boxShadow: {
        "mg-table": "0 10px 30px -22px var(--mg-shadow)",
        "mg-panel": "0 8px 24px -16px var(--mg-shadow)",
        "mg-modal": "0 16px 40px -12px rgba(0,0,0,0.4)",
        "mg-login": "0 30px 70px -28px var(--mg-shadow-lg)",
        "mg-focus": "0 0 0 4px var(--mg-purple-soft)",
      },
      keyframes: {
        mgDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        mgFade: {
          "0%": { opacity: "0", transform: "translateY(10px) scale(0.98)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        mgToast: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "mg-down": "mgDown 0.2s ease",
        "mg-fade": "mgFade 0.5s ease",
        "mg-toast": "mgToast 0.25s ease",
      },
    },
  },
  plugins: [],
} satisfies Config;
