"""add constrains to notification recioients

Revision ID: 09d027ebbc35
Revises: 43a704f553c1
Create Date: 2026-06-23 12:25:37.029073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d027ebbc35'
down_revision: Union[str, Sequence[str], None] = '43a704f553c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_notification_recipient', 'notification_recipient', ['notification_id', 'recipient_id'], schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notification_recipient', 'notification_recipient', schema='kcell_web', type_='unique')
    # ### end Alembic commands ###
