"""add original user to control

Revision ID: 0b1d75388d62
Revises: faf09dae21cc
Create Date: 2026-06-18 17:35:22.337114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1d75388d62'
down_revision: Union[str, Sequence[str], None] = 'faf09dae21cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем nullable
    op.add_column('control', sa.Column('original_user_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.create_foreign_key(None, 'control', 'user', ['original_user_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web')

    # 2. Бэкфилл — ставим original_user_id = responsible_id для существующих записей
    op.execute("UPDATE kcell_web.control SET original_user_id = responsible_id WHERE original_user_id IS NULL")

    # 3. Делаем NOT NULL
    op.alter_column('control', 'original_user_id', nullable=False, schema='kcell_web')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control', schema='kcell_web', type_='foreignkey')
    op.drop_column('control', 'original_user_id', schema='kcell_web')
    # ### end Alembic commands ###
