"""Add column is_og

Revision ID: 0ec50867beb9
Revises: 598ad34ac7d9
Create Date: 2026-06-16 14:42:05.658223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec50867beb9'
down_revision: Union[str, Sequence[str], None] = '598ad34ac7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'user',
        sa.Column('is_og', sa.Boolean(), nullable=True),
        schema='kcell_web'
    )
    op.execute('UPDATE kcell_web."user" SET is_og = false')
    op.alter_column('user', 'is_og', nullable=False, schema='kcell_web')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_og', schema='kcell_web')
    # ### end Alembic commands ###
