"""fix_taskstatus_enum_add_missing_values

Revision ID: 1537a29fa39f
Revises: e7d73f41f358
Create Date: 2026-06-17 14:12:16.037986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1537a29fa39f'
down_revision: Union[str, Sequence[str], None] = 'e7d73f41f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'IN_PROGRESS'")
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'COMPLETED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
