"""create mfs audit log

Revision ID: 36ccb96e6377
Revises: faee974c174f
Create Date: 2026-06-19 15:32:22.424015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ccb96e6377'
down_revision: Union[str, Sequence[str], None] = 'faee974c174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfs_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.Enum('BLOCK', 'UNBLOCK', 'CHECK', 'NOTE_ADD_FULL', 'NOTE_ADD_SHORT', 'NOTE_DELETE', name='action', schema='kcell_web'), nullable=False),
    sa.Column('msisdns_text', sa.Text(), nullable=False),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_ok', sa.Integer(), nullable=False),
    sa.Column('summary_skipped', sa.Integer(), nullable=False),
    sa.Column('summary_error', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kcell_web.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.create_index(op.f('ix_kcell_web_mfs_audit_log_id'), 'mfs_audit_log', ['id'], unique=False, schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kcell_web_mfs_audit_log_id'), table_name='mfs_audit_log', schema='kcell_web')
    op.drop_table('mfs_audit_log', schema='kcell_web')
    # ### end Alembic commands ###
