"""change attribute password_hash to hashed_password

Revision ID: 49a6650824c5
Revises: 8c6160ed279a
Create Date: 2026-06-15 20:47:13.875965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a6650824c5'
down_revision: Union[str, Sequence[str], None] = '8c6160ed279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=256), nullable=False), schema='kcell_web')
    op.drop_column('user', 'password_hash', schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False), schema='kcell_web')
    op.drop_column('user', 'hashed_password', schema='kcell_web')
    # ### end Alembic commands ###
