"""correct max symbols to priority attribute

Revision ID: 598ad34ac7d9
Revises: c7bfd4fdaa46
Create Date: 2026-06-16 10:34:49.802243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598ad34ac7d9'
down_revision: Union[str, Sequence[str], None] = 'c7bfd4fdaa46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control', 'priority',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False,
               schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control', 'priority',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               schema='kcell_web')
    # ### end Alembic commands ###
