"""Delete column date

Revision ID: 5a9b73ccb03c
Revises: c5928ccd1d83
Create Date: 2026-06-17 09:07:37.828884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9b73ccb03c'
down_revision: Union[str, Sequence[str], None] = 'c5928ccd1d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'date', schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False), schema='kcell_web')
    # ### end Alembic commands ###
