"""turn on nullable true to control model

Revision ID: 5fd83a6c92e8
Revises: 1537a29fa39f
Create Date: 2026-06-17 14:33:30.757213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd83a6c92e8'
down_revision: Union[str, Sequence[str], None] = '1537a29fa39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='kcell_web')
    op.alter_column('control', 'dashboard_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('control', 'dashboard_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               schema='kcell_web')
    op.alter_column('control', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='kcell_web')
    # ### end Alembic commands ###
