"""delete column deadline_at

Revision ID: a207ee23a100
Revises: fd0081fe80d4
Create Date: 2026-06-17 16:57:35.197488

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a207ee23a100"
down_revision: str | Sequence[str] | None = "fd0081fe80d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("control", "deadline_at", schema="kcell_web")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "control",
        sa.Column(
            "deadline_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        schema="kcell_web",
    )
    # ### end Alembic commands ###
