"""Create table task

Revision ID: a6c790797405
Revises: 0ec50867beb9
Create Date: 2026-06-16 15:05:28.964980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6c790797405"
down_revision: str | Sequence[str] | None = "0ec50867beb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("NOT_STARTED", name="taskstatus"), nullable=False),
        sa.Column("weekend_group_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["kcell_web.control.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kcell_web.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weekend_group_id"],
            ["kcell_web.task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_task_id"), "task", ["id"], unique=False, schema="kcell_web"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kcell_web_task_id"), table_name="task", schema="kcell_web")
    op.drop_table("task", schema="kcell_web")
    # ### end Alembic commands ###
