"""create control table

Revision ID: c7bfd4fdaa46
Revises: 49a6650824c5
Create Date: 2026-06-16 10:28:10.740867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bfd4fdaa46'
down_revision: Union[str, Sequence[str], None] = '49a6650824c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('time_estimate', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'AS_REQUIRED', name='frequency'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('risk', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=False),
    sa.Column('dashboard_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='controlstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['kcell_web.user.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['kcell_web.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.create_index(op.f('ix_kcell_web_control_id'), 'control', ['id'], unique=False, schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kcell_web_control_id'), table_name='control', schema='kcell_web')
    op.drop_table('control', schema='kcell_web')
    # ### end Alembic commands ###
