"""create column deadlime_time

Revision ID: dabcf879ad2b
Revises: 5a9b73ccb03c
Create Date: 2026-06-17 09:21:40.065673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabcf879ad2b'
down_revision: Union[str, Sequence[str], None] = '5a9b73ccb03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deadline_time', sa.DateTime(), nullable=True), schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deadline_time', schema='kcell_web')
    # ### end Alembic commands ###
