"""create new table incident and fix task table

Revision ID: faee974c174f
Revises: 74872acba043
Create Date: 2026-06-19 10:08:19.793845

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faee974c174f"
down_revision: str | Sequence[str] | None = "74872acba043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "Открыт",
                "На согласовании",
                "Согласован",
                "Отклонён",
                name="incidentstatus",
                schema="kcell_web",
            ),
            nullable=False,
        ),
        sa.Column("control_type", sa.String(length=255), nullable=False),
        sa.Column("control_subtype", sa.String(length=255), nullable=False),
        sa.Column("risk", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("problem_area", sa.String(length=255), nullable=True),
        sa.Column("detected_source", sa.String(length=255), nullable=False),
        sa.Column("reporting_month", sa.Date(), nullable=False),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("solution_date", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("incident_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column("taken_measures", sa.String(length=4000), nullable=True),
        sa.Column("root_cause", sa.String(length=255), nullable=True),
        sa.Column("estimated_loss", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("opportunity_loss", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("bad_debt", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "prevented_savings", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "recovered_savings", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("overchange", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("service_abused", sa.String(length=255), nullable=True),
        sa.Column("count_fraudulent_numbers", sa.Integer(), nullable=True),
        sa.Column("case_type", sa.String(length=50), nullable=False),
        sa.Column("attachment", sa.String(length=2000), nullable=True),
        sa.Column("kpi_calculation", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "confirmed_fraud",
            sa.Enum("Да", "Нет", name="confirmed_fraud", schema="kcell_web"),
            nullable=True,
        ),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["kcell_web.task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_incident_id"),
        "incident",
        ["id"],
        unique=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kcell_web_incident_id"), table_name="incident", schema="kcell_web"
    )
    op.drop_table("incident", schema="kcell_web")
    # ### end Alembic commands ###
