"""create vacation shedule table

Revision ID: faf09dae21cc
Revises: dd99a503d892
Create Date: 2026-06-18 14:04:59.306832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faf09dae21cc"
down_revision: str | Sequence[str] | None = "dd99a503d892"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacation_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "vacation_type",
            sa.Enum(
                "ANNUAL_LEAVE",
                "SICK_LEAVE",
                "BUSINESS_TRIP",
                name="vacation_type",
                schema="kcell_web",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELLED", name="vacation_status", schema="kcell_web"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kcell_web.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_vacation_schedule_id"),
        "vacation_schedule",
        ["id"],
        unique=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kcell_web_vacation_schedule_id"),
        table_name="vacation_schedule",
        schema="kcell_web",
    )
    op.drop_table("vacation_schedule", schema="kcell_web")
    # ### end Alembic commands ###
