"""add must_change_password to user

Revision ID: 014947d9ec74
Revises: 9050db248c93
Create Date: 2026-07-23 15:27:36.897334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014947d9ec74'
down_revision: Union[str, Sequence[str], None] = '9050db248c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False), schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password', schema='kcell_web')
    # ### end Alembic commands ###
