"""add new columns as can read and can edit in me_not

Revision ID: 02e8961c332f
Revises: e0ab1d1f39c5
Create Date: 2026-07-27 10:12:07.757385

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02e8961c332f"
down_revision: str | Sequence[str] | None = "e0ab1d1f39c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "me_note",
        sa.Column(
            "can_edit_ids", sa.ARRAY(sa.Integer()), server_default="{}", nullable=False
        ),
        schema="kcell_web",
    )
    op.add_column(
        "me_note",
        sa.Column(
            "can_read_ids", sa.ARRAY(sa.Integer()), server_default="{}", nullable=False
        ),
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("me_note", "can_read_ids", schema="kcell_web")
    op.drop_column("me_note", "can_edit_ids", schema="kcell_web")
    # ### end Alembic commands ###
