"""revision

Revision ID: 1015870c9630
Revises: 8253db0234a1
Create Date: 2026-06-22 17:06:04.092141

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1015870c9630"
down_revision: str | Sequence[str] | None = "8253db0234a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
