"""alter column

Revision ID: 23a5fee22336
Revises: 2c8e472088aa
Create Date: 2026-08-11 13:52:05.985659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a5fee22336'
down_revision: Union[str, Sequence[str], None] = '2c8e472088aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tele2_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'PENDING', name='log_status', schema='kcell_web'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kcell_web.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tele2_log', schema='kcell_web')
    # ### end Alembic commands ###
