"""new table

Revision ID: 40367f3a23ef
Revises: d43025dbb818
Create Date: 2026-08-31 15:50:32.850196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40367f3a23ef'
down_revision: Union[str, Sequence[str], None] = 'd43025dbb818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('iin', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('client_category', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('client_status', sa.String(), nullable=True),
    sa.Column('comment_about_client', sa.String(), nullable=True),
    sa.Column('privilege_sign', sa.Boolean(), nullable=True),
    sa.Column('activation_date', sa.Date(), nullable=True),
    sa.Column('subscriber_activation_date', sa.Date(), nullable=True),
    sa.Column('imsi', sa.String(), nullable=True),
    sa.Column('imsi_2', sa.String(), nullable=True),
    sa.Column('number_status', sa.String(), nullable=True),
    sa.Column('sim_card_type', sa.String(), nullable=True),
    sa.Column('icc', sa.String(), nullable=True),
    sa.Column('sim_card_status_now', sa.String(), nullable=True),
    sa.Column('sim_card_status_historical', sa.String(), nullable=True),
    sa.Column('sim_card_expiration_date', sa.Date(), nullable=True),
    sa.Column('diller', sa.String(), nullable=True),
    sa.Column('diller_number', sa.String(), nullable=True),
    sa.Column('registration_chanel', sa.String(), nullable=True),
    sa.Column('subscriber_status', sa.String(), nullable=True),
    sa.Column('lock_calls', sa.Boolean(), nullable=True),
    sa.Column('subscriber_close_date', sa.Date(), nullable=True),
    sa.Column('network_type', sa.String(), nullable=True),
    sa.Column('subscriber_lc_status', sa.String(), nullable=True),
    sa.Column('lc_status_change_date', sa.Date(), nullable=True),
    sa.Column('balance_end_date', sa.Date(), nullable=True),
    sa.Column('roaming_type', sa.String(), nullable=True),
    sa.Column('tariff_plan_id', sa.Integer(), nullable=True),
    sa.Column('name_of_tariff_plan', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accounts_receivable_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_of_last_balance_change', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dealer_name', sa.String(), nullable=True),
    sa.Column('contract_sign_date', sa.Date(), nullable=True),
    sa.Column('dealer_iin', sa.String(), nullable=True),
    sa.Column('dealer_phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.create_index(op.f('ix_kcell_web_number_information_phone_number'), 'number_information', ['phone_number'], unique=False, schema='kcell_web')
    op.create_table('number_information_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sql_request', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number_information_login', schema='kcell_web')
    op.drop_index(op.f('ix_kcell_web_number_information_phone_number'), table_name='number_information', schema='kcell_web')
    op.drop_table('number_information', schema='kcell_web')
    # ### end Alembic commands ###
