"""add responsible user to notification table

Revision ID: 43a704f553c1
Revises: c840e47a3969
Create Date: 2026-06-23 11:27:28.962044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a704f553c1'
down_revision: Union[str, Sequence[str], None] = 'c840e47a3969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('responsible_user_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.create_foreign_key(None, 'notification', 'user', ['responsible_user_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web', ondelete='SET NULL')
    op.drop_constraint(op.f('uq_notification_recipient'), 'notification_recipient', schema='kcell_web', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_notification_recipient'), 'notification_recipient', ['notification_id', 'recipient_id'], schema='kcell_web', postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notification', schema='kcell_web', type_='foreignkey')
    op.drop_column('notification', 'responsible_user_id', schema='kcell_web')
    # ### end Alembic commands ###
