"""add new table directory

Revision ID: 43d75292f31c
Revises: becfdac9aac2
Create Date: 2026-07-08 17:56:31.487761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d75292f31c'
down_revision: Union[str, Sequence[str], None] = 'becfdac9aac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.add_column('me_note', sa.Column('directory_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.create_foreign_key(None, 'me_note', 'directory', ['directory_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'me_note', schema='kcell_web', type_='foreignkey')
    op.drop_column('me_note', 'directory_id', schema='kcell_web')
    op.drop_table('directory', schema='kcell_web')
    # ### end Alembic commands ###
