"""delete notification type

Revision ID: 483e408a7c6d
Revises: 02e8961c332f
Create Date: 2026-07-27 12:02:24.046473

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "483e408a7c6d"
down_revision: str | Sequence[str] | None = "02e8961c332f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "notification_type", schema="kcell_web")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "TASK_CREATED",
                "TASK_UPDATED",
                "INCIDENT_UPDATED",
                name="notificationtypes",
                schema="kcell_web",
            ),
            autoincrement=False,
            nullable=False,
        ),
        schema="kcell_web",
    )
    # ### end Alembic commands ###
