"""add new enum overdue to tasks

Revision ID: 4bc489b37bf0
Revises: 9d8f7e6c5b4a
Create Date: 2026-06-29 11:59:33.845075

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bc489b37bf0"
down_revision: str | Sequence[str] | None = "9d8f7e6c5b4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE kcell_web.taskstatus ADD VALUE 'OVERDUE'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
