"""add column email to user

Revision ID: 4daddee56bc6
Revises: 36ccb96e6377
Create Date: 2026-06-22 11:48:50.269872

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4daddee56bc6"
down_revision: str | Sequence[str] | None = "36ccb96e6377"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "user",
        sa.Column("email", sa.String(length=64), nullable=True),
        schema="kcell_web",
    )
    op.execute(
        "UPDATE kcell_web.\"user\" SET email = 'unknown_' || id::text || '@kcell.kz' WHERE email IS NULL"
    )
    op.alter_column("user", "email", nullable=False, schema="kcell_web")
    op.create_unique_constraint(None, "user", ["email"], schema="kcell_web")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", schema="kcell_web", type_="unique")
    op.drop_column("user", "email", schema="kcell_web")
    # ### end Alembic commands ###
