"""update table with relationships me_note

Revision ID: 4dcb00ce743d
Revises: b767417cca21
Create Date: 2026-07-07 15:03:33.470924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dcb00ce743d'
down_revision: Union[str, Sequence[str], None] = 'b767417cca21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_note', 'mime_type',
               existing_type=postgresql.ENUM('PDF', 'MD', 'HTML', 'JPEG', 'XLS', 'XLSX', 'CSV', 'DOCX', name='mime_types', schema='kcell_web'),
               nullable=True,
               schema='kcell_web')
    op.alter_column('me_note', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='kcell_web')
    op.alter_column('me_note', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_note', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='kcell_web')
    op.alter_column('me_note', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='kcell_web')
    op.alter_column('me_note', 'mime_type',
               existing_type=postgresql.ENUM('PDF', 'MD', 'HTML', 'JPEG', 'XLS', 'XLSX', 'CSV', 'DOCX', name='mime_types', schema='kcell_web'),
               nullable=False,
               schema='kcell_web')
    # ### end Alembic commands ###
