"""update table me_note by deleting saving files

Revision ID: 599f63e2c34e
Revises: 4dcb00ce743d
Create Date: 2026-07-08 09:36:44.519623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599f63e2c34e'
down_revision: Union[str, Sequence[str], None] = '4dcb00ce743d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_note', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False), schema='kcell_web')
    op.add_column('me_note', sa.Column('content', sa.Text(), nullable=True), schema='kcell_web')
    op.add_column('me_note', sa.Column('editor_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.create_foreign_key(None, 'me_note', 'user', ['editor_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web', ondelete='SET NULL')
    op.drop_column('me_note', 'file_path', schema='kcell_web')
    op.drop_column('me_note', 'mime_type', schema='kcell_web')
    op.drop_column('me_note', 'file_size', schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_note', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True), schema='kcell_web')
    op.add_column('me_note', sa.Column('mime_type', postgresql.ENUM('PDF', 'MD', 'HTML', 'JPEG', 'XLS', 'XLSX', 'CSV', 'DOCX', name='mime_types', schema='kcell_web'), autoincrement=False, nullable=True), schema='kcell_web')
    op.add_column('me_note', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True), schema='kcell_web')
    op.drop_constraint(None, 'me_note', schema='kcell_web', type_='foreignkey')
    op.drop_column('me_note', 'editor_id', schema='kcell_web')
    op.drop_column('me_note', 'content', schema='kcell_web')
    op.drop_column('me_note', 'tags', schema='kcell_web')
    # ### end Alembic commands ###
