"""Change column type date to datetime in task table

Revision ID: 697c76a03999
Revises: a6c790797405
Create Date: 2026-06-16 16:05:55.173416

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "697c76a03999"
down_revision: str | Sequence[str] | None = "a6c790797405"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###
