"""fix relationship in original user id

Revision ID: 74872acba043
Revises: b96d1913e935
Create Date: 2026-06-18 17:52:12.260607

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "74872acba043"
down_revision: str | Sequence[str] | None = "b96d1913e935"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
