"""add approved_by and rejected_by fields to incident

Revision ID: 76e4480f4480
Revises: 6f0b0d0a9412
Create Date: 2026-08-21 10:16:02.457577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e4480f4480'
down_revision: Union[str, Sequence[str], None] = '6f0b0d0a9412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('approved_by_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.add_column('incident', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), schema='kcell_web')
    op.add_column('incident', sa.Column('rejected_by_id', sa.Integer(), nullable=True), schema='kcell_web')
    op.add_column('incident', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True), schema='kcell_web')
    op.create_foreign_key(None, 'incident', 'user', ['rejected_by_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web', ondelete='SET NULL')
    op.create_foreign_key(None, 'incident', 'user', ['approved_by_id'], ['id'], source_schema='kcell_web', referent_schema='kcell_web', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', schema='kcell_web', type_='foreignkey')
    op.drop_constraint(None, 'incident', schema='kcell_web', type_='foreignkey')
    op.drop_column('incident', 'rejected_at', schema='kcell_web')
    op.drop_column('incident', 'rejected_by_id', schema='kcell_web')
    op.drop_column('incident', 'approved_at', schema='kcell_web')
    op.drop_column('incident', 'approved_by_id', schema='kcell_web')
    # ### end Alembic commands ###
