"""change JSONB from Text in content

Revision ID: 79944cf3271f
Revises: 43d75292f31c
Create Date: 2026-07-13 10:00:07.838704

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79944cf3271f"
down_revision: str | Sequence[str] | None = "43d75292f31c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("UPDATE kcell_web.me_note SET content = NULL")
    op.alter_column(
        "me_note",
        "content",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="content::jsonb",
        schema="kcell_web",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "me_note",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema="kcell_web",
    )
    # ### end Alembic commands ###
