"""history

Revision ID: 8253db0234a1
Revises: acaa30e72fd3
Create Date: 2026-06-22 17:05:30.072420

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8253db0234a1"
down_revision: str | Sequence[str] | None = "acaa30e72fd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
