"""add start and end time to notification table

Revision ID: 877b09922a27
Revises: 0160df5fb1e1
Create Date: 2026-07-15 14:46:35.562955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877b09922a27'
down_revision: Union[str, Sequence[str], None] = '0160df5fb1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True), schema='kcell_web')
    op.add_column('notification', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True), schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'end_time', schema='kcell_web')
    op.drop_column('notification', 'start_time', schema='kcell_web')
    # ### end Alembic commands ###
