"""add last_version columb

Revision ID: 9050db248c93
Revises: c7edfd38cc8a
Create Date: 2026-07-20 16:25:09.345382

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9050db248c93"
down_revision: str | Sequence[str] | None = "c7edfd38cc8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "me_note",
        sa.Column(
            "last_version", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("me_note", "last_version", schema="kcell_web")
    # ### end Alembic commands ###
