"""add new enum DEV area to control

Revision ID: 9c1dedc8bd2c
Revises: 4228f98a812a
Create Date: 2026-06-30 16:38:11.870785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1dedc8bd2c'
down_revision: Union[str, Sequence[str], None] = '4228f98a812a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE kcell_web.area ADD VALUE 'DEV'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
