"""create tables notification and notification_recipient

Revision ID: acaa30e72fd3
Revises: 4daddee56bc6
Create Date: 2026-06-22 13:46:12.034057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaa30e72fd3'
down_revision: Union[str, Sequence[str], None] = '4daddee56bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('TASK_CREATED', 'TASK_UPDATED', 'INCIDENT_UPDATED', name='notificationtypes', schema='kcell_web'), nullable=False),
    sa.Column('recipients_email', sa.String(length=4000), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('html_content', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.create_index(op.f('ix_kcell_web_notification_id'), 'notification', ['id'], unique=False, schema='kcell_web')
    op.create_table('notification_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['kcell_web.notification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['kcell_web.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    op.create_index(op.f('ix_kcell_web_notification_recipient_id'), 'notification_recipient', ['id'], unique=False, schema='kcell_web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kcell_web_notification_recipient_id'), table_name='notification_recipient', schema='kcell_web')
    op.drop_table('notification_recipient', schema='kcell_web')
    op.drop_index(op.f('ix_kcell_web_notification_id'), table_name='notification', schema='kcell_web')
    op.drop_table('notification', schema='kcell_web')
    # ### end Alembic commands ###
