"""create table me_note

Revision ID: b767417cca21
Revises: 9c1dedc8bd2c
Create Date: 2026-07-07 12:52:23.501220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b767417cca21'
down_revision: Union[str, Sequence[str], None] = '9c1dedc8bd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('me_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.Enum('PDF', 'MD', 'HTML', 'JPEG', 'XLS', 'XLSX', 'CSV', 'DOCX', name='mime_types', schema='kcell_web'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.Column('last_modifier_id', sa.Integer(), nullable=True),
    sa.Column('is_editing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['kcell_web.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modifier_id'], ['kcell_web.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='kcell_web'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('me_note', schema='kcell_web')
    # ### end Alembic commands ###
