"""create 2 new tables

Revision ID: c22836326dc6
Revises: 483e408a7c6d
Create Date: 2026-07-27 16:03:32.916395

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c22836326dc6"
down_revision: str | Sequence[str] | None = "483e408a7c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "me_note_editors",
        sa.Column("me_note_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["me_note_id"], ["kcell_web.me_note.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["kcell_web.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("me_note_id", "user_id"),
        schema="kcell_web",
    )
    op.create_table(
        "me_note_readers",
        sa.Column("me_note_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["me_note_id"], ["kcell_web.me_note.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["kcell_web.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("me_note_id", "user_id"),
        schema="kcell_web",
    )
    op.drop_column("me_note", "can_read_ids", schema="kcell_web")
    op.drop_column("me_note", "can_edit_ids", schema="kcell_web")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "me_note",
        sa.Column(
            "can_edit_ids",
            postgresql.ARRAY(sa.INTEGER()),
            server_default=sa.text("'{}'::integer[]"),
            autoincrement=False,
            nullable=False,
        ),
        schema="kcell_web",
    )
    op.add_column(
        "me_note",
        sa.Column(
            "can_read_ids",
            postgresql.ARRAY(sa.INTEGER()),
            server_default=sa.text("'{}'::integer[]"),
            autoincrement=False,
            nullable=False,
        ),
        schema="kcell_web",
    )
    op.drop_table("me_note_readers", schema="kcell_web")
    op.drop_table("me_note_editors", schema="kcell_web")
    # ### end Alembic commands ###
