"""create user table

Revision ID: ca359650b32f
Revises:
Create Date: 2026-06-15 19:42:49.569814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca359650b32f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userroles", schema="kcell_web"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_user_id"), "user", ["id"], unique=False, schema="kcell_web"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kcell_web_user_id"), table_name="user", schema="kcell_web")
    op.drop_table("user", schema="kcell_web")
    # ### end Alembic commands ###
