"""add me_note_link

Revision ID: d1c9f200a8f3
Revises: 877b09922a27
Create Date: 2026-07-16 09:49:08.854089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1c9f200a8f3"
down_revision: str | Sequence[str] | None = "877b09922a27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "me_note_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_note_id", sa.Integer(), nullable=False),
        sa.Column("target_note_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_note_id"], ["kcell_web.me_note.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_note_id"], ["kcell_web.me_note.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("me_note_link", schema="kcell_web")
    # ### end Alembic commands ###
