"""add indexes to control and task tables

Revision ID: d609fbad0229
Revises: fb2d4b332ed3
Create Date: 2026-06-26 09:30:36.120996

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d609fbad0229"
down_revision: str | Sequence[str] | None = "fb2d4b332ed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_kcell_web_control_backup_id"),
        "control",
        ["backup_id"],
        unique=False,
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_control_original_user_id"),
        "control",
        ["original_user_id"],
        unique=False,
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_control_responsible_id"),
        "control",
        ["responsible_id"],
        unique=False,
        schema="kcell_web",
    )
    op.create_index(
        op.f("ix_kcell_web_task_control_id"),
        "task",
        ["control_id"],
        unique=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kcell_web_task_control_id"), table_name="task", schema="kcell_web"
    )
    op.drop_index(
        op.f("ix_kcell_web_control_responsible_id"),
        table_name="control",
        schema="kcell_web",
    )
    op.drop_index(
        op.f("ix_kcell_web_control_original_user_id"),
        table_name="control",
        schema="kcell_web",
    )
    op.drop_index(
        op.f("ix_kcell_web_control_backup_id"), table_name="control", schema="kcell_web"
    )
    # ### end Alembic commands ###
