"""create tags

Revision ID: e08b5b687739
Revises: 79944cf3271f
Create Date: 2026-07-15 10:30:21.023757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08b5b687739'
down_revision: Union[str, Sequence[str], None] = '79944cf3271f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('me_note_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('me_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['me_note_id'], ['kcell_web.me_note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['kcell_web.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'me_note_id'),
    schema='kcell_web'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('me_note_tags', schema='kcell_web')
    # ### end Alembic commands ###
