"""change default of must_change_password

Revision ID: e0ab1d1f39c5
Revises: 014947d9ec74
Create Date: 2026-07-24 09:40:19.964506

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e0ab1d1f39c5"
down_revision: str | Sequence[str] | None = "014947d9ec74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
