"""fix_deadline_time_type

Revision ID: ef888c2d6c8d
Revises: a1b2c3d4e5f6
Create Date: 2026-06-17 13:51:39.059554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef888c2d6c8d"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "deadline_time",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema="kcell_web",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "deadline_time",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="kcell_web",
    )
    # ### end Alembic commands ###
