"""add indexes to control and task tables

Revision ID: f4b9a0d60ee2
Revises: d609fbad0229
Create Date: 2026-06-26 09:34:46.193334

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4b9a0d60ee2"
down_revision: str | Sequence[str] | None = "d609fbad0229"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kcell_web_control_id"), table_name="control", schema="kcell_web"
    )
    op.drop_index(op.f("ix_kcell_web_task_id"), table_name="task", schema="kcell_web")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_kcell_web_task_id"), "task", ["id"], unique=False, schema="kcell_web"
    )
    op.create_index(
        op.f("ix_kcell_web_control_id"),
        "control",
        ["id"],
        unique=False,
        schema="kcell_web",
    )
    # ### end Alembic commands ###
