"""add column first name and last name to user table

Revision ID: fb2d4b332ed3
Revises: 09d027ebbc35
Create Date: 2026-06-25 10:44:39.788490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb2d4b332ed3"
down_revision: str | Sequence[str] | None = "09d027ebbc35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("first_name", sa.String(), nullable=True), schema="kcell_web"
    )
    op.add_column(
        "user", sa.Column("last_name", sa.String(), nullable=True), schema="kcell_web"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name", schema="kcell_web")
    op.drop_column("user", "first_name", schema="kcell_web")
    # ### end Alembic commands ###
