"""correct relation between control and task

Revision ID: fd0081fe80d4
Revises: 5fd83a6c92e8
Create Date: 2026-06-17 14:55:46.340533

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fd0081fe80d4"
down_revision: str | Sequence[str] | None = "5fd83a6c92e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
